### ISSUE TITLE
代码不能跑出效果

### ISSUE THREAD

**Issue by TBWSZZ** [ShenZheng2000/Semantic-Guided-Low-Light-Image-Enhancement#2]
您好，请问下具体的参数设置是什么，我使用您的模型不能达到您论文中的效果，谢谢您。

**Comment by ShenZheng2000** [comment]
你好，请问您说的“效果”，是指图片的视觉效果吗，还是图片的PSNR等数值。

如果是前者的话，我可以对比下你得到的图片，和我得到的图片，看看差别在哪。

如果是后者的话，PSNR，SSIM等，不同package算出来的值会相差很大，是否使用grayscale, multichannel等，也有一定的影响。一般来说，Matlab>低版本的sklearn>=高版本的sklearn。

**Comment by TBWSZZ** [comment]
好的，谢谢您
