### ISSUE TITLE
metric of Tab.5 

### ISSUE THREAD

**Issue by zhebawomenjiuyaochangshenle** [ShenZheng2000/Semantic-Guided-Low-Light-Image-Enhancement#3]
Hello, I want to reproduce the results of Table 5 in the paper, but I find that the metrics (BRISQUE) of both Dark and Zero-DCE are quite different from those in the paper. Can you tell me how you calculated the metrics? I would appreciate it if you could give me the metric calculation method.

**Comment by ShenZheng2000** [comment]
I appreciate your inquiry. Currently, I'm occupied with another project deadline, but I plan to go through and tidy up the old code repository within the next 2 weeks.

As far as I can recall, I used one of the following three libraries for brisque:

(1) https://pypi.org/project/image-quality/
(2) https://pypi.org/project/brisque/
(3) https://github.com/bukalapak/pybrisque

Please let me know if any further questions.

**Comment by zhebawomenjiuyaochangshenle** [comment]
Hello, thank you for your reply. I was recently evaluating the enhanced image indicators, but found a big difference from the indicators in other papers, looking forward to your code, thank you for your maintenance of the project.
