### ISSUE TITLE
非配对增强

### ISSUE THREAD

**Issue by Maozhiquan** [ShenZheng2000/Semantic-Guided-Low-Light-Image-Enhancement#5]
感谢作者伟大的工作! 我想请问关于非配对训练亮度增强的问题，因为我在使用自己模型的时候发现亮度提升非常不明显，基本只提升了一点点，作者您这篇工作亮度提升为什么如此大主要是由于Brightness Loss 吗？我不确定这个是否可以用于我的非配对模型来提升增强亮度，如果作者可以回我我真的万分感激，祝作者事业生活顺利!

**Comment by ShenZheng2000** [comment]
你好！感谢你对我工作的兴趣！

这项工作在亮度提升方面表现出色，我认为有两个主要原因：
（1）Brightness Loss: 由于设计中使用了0.6 out of 0-1 scale，这帮助**整体亮度**达到一个更理想的效果。
（2）增强因子（Enhancement Factor）: 它使**局部亮度**能够自适应地调整。具体来说，暗部区域会被增强得更多（减少欠曝），而亮部区域则被增强得较少或保持不变（抑制过曝），从而提供更舒适的视觉体验。

关于是否可以用于非配对模型：
(1) Brightness Loss: 比较简单，你可以直接尝试应用，看看效果如何。
(2) Enhancement Factor: 复杂一些，因为它依赖多方面的 zero-shot loss（参见论文 Section 3.4），所以不一定适用非配对模型。但是，你可以参考 Section 3.2 的公式 (1)，将 Enhancement Factor 嵌入到 Encoder 前的某个步骤，以帮助优化局部亮度。

**Comment by Maozhiquan** [comment]
> 你好！感谢你对我工作的兴趣！
> 
> 这项工作在亮度提升方面表现出色，我认为有两个主要原因： （1）Brightness Loss: 由于设计中使用了0.6 out of 0-1 scale，这帮助**整体亮度**达到一个更理想的效果。 （2）增强因子（Enhancement Factor）: 它使**局部亮度**能够自适应地调整。具体来说，暗部区域会被增强得更多（减少欠曝），而亮部区域则被增强得较少或保持不变（抑制过曝），从而提供更舒适的视觉体验。
> 
> 关于是否可以用于非配对模型： (1) Brightness Loss: 比较简单，你可以直接尝试应用，看看效果如何。 (2) Enhancement Factor: 复杂一些，因为它依赖多方面的 zero-shot loss（参见论文 Section 3.4），所以不一定适用非配对模型。但是，你可以参考 Section 3.2 的公式 (1)，将 Enhancement Factor 嵌入到 Encoder 前的某个步骤，以帮助优化局部亮度。

太谢谢您了！！！我马上在我的模型里面试试您说的第二个增强因子，永远感恩，祝您生活事业顺利，祉猷并茂！！！
