### ISSUE TITLE
非配对效果

### ISSUE THREAD

**Issue by Maozhiquan** [ShenZheng2000/Semantic-Guided-Low-Light-Image-Enhancement#6]
不好意思，作者我又来了，我试了试您论文中Brightness Loss和RGB Loss，亮度确实增强了很多，可是整张图片也像蒙了一层发白的滤镜，请问这种情况我应该从哪个方向寻求改进？小白的我感觉有两个但是不知道是否正确：1.加上mask让前景学习更突出，以此来消除这种整体发白的滤镜 2. 不使用这俩损失，寻求其他亮度增强的办法（比如换一个生成器的backbone）。我的图片是2000*3000的，可能太高清了不好学习也有可能，如果作者大大还能给点指点的话，我就真的真的太感恩了
![42f9c006a6df73739767476a999a67a](https://github.com/ShenZheng2000/Semantic-Guided-Low-Light-Image-Enhancement/assets/92560709/c6221515-526e-4408-83a5-4cd3440585fc)

**Comment by ShenZheng2000** [comment]
1. **颜色和感知损失：** 我还没有尝试过使用mask的方法，所以不确定它是否有效。不过，从你提供的图像的视觉效果来看，使用一个经过良好调整的Color Loss（论文里的RGB Loss）可能可以改善图像质量。你也可以考虑使用基于神经网络的Perceptual Losses，它们在评估图像相似度和质量方面可能表现更好。

2. **增强因子和主干网络的强度：** 在我的论文中，我采用了深度可分离卷积（Depthwise Separable Convolution）来设计一个轻量化的增强因子。这种方法对低分辨率图像来说，捕捉局部的光照不足是足够的。但是，对于像2k*3k这样高分辨率的图像，可能需要一个更强大的主干网络。你可以参考这篇专门讨论高分辨率低光增强的论文：[Ultra-High-Definition Low-Light Image Enhancement: A Benchmark and Transformer-Based Method](https://arxiv.org/pdf/2212.11548)

**Comment by Maozhiquan** [comment]
> 1. **颜色和感知损失：** 我还没有尝试过使用mask的方法，所以不确定它是否有效。不过，从你提供的图像的视觉效果来看，使用一个经过良好调整的Color Loss（论文里的RGB Loss）可能可以改善图像质量。你也可以考虑使用基于神经网络的Perceptual Losses，它们在评估图像相似度和质量方面可能表现更好。
> 2. **增强因子和主干网络的强度：** 在我的论文中，我采用了深度可分离卷积（Depthwise Separable Convolution）来设计一个轻量化的增强因子。这种方法对低分辨率图像来说，捕捉局部的光照不足是足够的。但是，对于像2k*3k这样高分辨率的图像，可能需要一个更强大的主干网络。你可以参考这篇专门讨论高分辨率低光增强的论文：[Ultra-High-Definition Low-Light Image Enhancement: A Benchmark and Transformer-Based Method](https://arxiv.org/pdf/2212.11548)

太谢谢您了！看到您这个回答我真的哭了，谢谢您指导一个处在迷茫期的我，您就是一束光，我会好好去看看这篇论文的，最后再次谢谢您，祝您身体健康 万事顺遂！
