### ISSUE TITLE
PSNR,SSIM

### ISSUE THREAD

**Issue by lanbowan1** [ShenZheng2000/Semantic-Guided-Low-Light-Image-Enhancement#7]
Hi, I have tested and used the pre-training weights file（weight/Epoch99.pth） you gave and added PSNR with SSIM  calculations and found that the values are very different, can you please help me to analyse the reason? psnr（10.60）and ssim（0.36）
![微信图片_20240724192723](https://github.com/user-attachments/assets/57c9b3ba-2932-444f-98bd-bc962366985f)

**Comment by ShenZheng2000** [comment]
Apologies for the delayed response; my old email address linked to GitHub has expired.

PSNR and SSIM values vary significantly depending on the implementation and the version of the package used. Unfortunately, I cannot recall the exact package and version I used, as it has been three years. 

However, you can compare the visual results with those presented in my paper. If you notice any inconsistencies, please let me know, and I will double-check the checkpoints. Besides, you can show me your implementations of PSNR and SSIM, and I can look at it.
